#!/bin/tcsh
#
# take a PRIDE-PPPAR kin_* solution file and split
# it into 2 files, 1 containing just header info
# and 1 containing just solution/processed data
#
# INPUT:
#
# kin solution file    output file created by PRIDE-PPPAR containing PPP solutions
#
# OUTPUT:
#
# solutions.hdr        file only containing header information from input kin file
# solutions.prd        file only containing solution information from input kin file
#
# Originally written by tschuh-at-princeton.edu, 10/06/2021

set infile = $1

set hdrend = `rnx2hdr $infile`
set hdrend = `echo "$hdrend+1" | bc`

awk 'NR<'"$hdrend"' {print}' $infile >! solutions.hdr
awk 'NR>'"$hdrend"' {print}' $infile >! solutions.prd


