#!/bin/tcsh
#
# takes a RINEX file and outputs to screen the number of satellites used
#
# INPUT:
#
# $1      RINEX file
#
# OUTPUT:
#
# number of satellites to screen
#
# Last modified by tschuh-at-princeton.edu, 06/15/2021

# blocks in a RINEX file can fit up to 5 data observations per line
# sat <= 5 --> 1 line of data
# 5 < sat <= 10 --> 2 lines of data
# sat > 10 --> 3 lines of data

set sat = `awk '/TYPES OF OBSERV/ {print $1; exit}' $1`

if ($sat <= 5) then
    printf "There are %2.2i satellites used in this RINEX file.\nThere is 1 line per data entry.\n" $sat
else if (5 < $sat && $sat <= 10) then
    printf "There are %2.2i satellites used in this RINEX file.\nThere are 2 lines per data entry.\n" $sat
else
    printf "There are %2.2i satellites used in this RINEX file.\nThere are 3 lines per data entry.\n" $sat
endif
