#!/bin/tcsh

# this script will take a RINEX file and determine if it's missing any
# seconds of measurements

set hlength = `./rinex2hdr $1`

# text match all the dates in the RINEX file
# convert dates to seconds using GipsyX command date2sec
# go through every line and subtract the value on the previous line
set dum = `awk '/[A-z]/ && NR>'"$hlength"' && $1!~/[A-z]/ {printf "20%2.2i-%2.2i-%2.2i %2.2i:%2.2i:%2.2i\n",$1,$2,$3,$4,$5,$6}' $1 | date2sec | awk 'NR > 1 { print $0 - prev } { prev = $0 }'`

# if the difference between lines is something
# other than 1, then report this (make variable err)
foreach num ($dum[*])
    if ($num != 1) then
       set err = "0"
    endif
end

# test the existence of the variable err
# if it exists, then kill the next program
# otherwise continue
if ( $?err ) then
    echo "TEST FAILED"
else
    echo "TEST SUCCESSFUL"
endif

