#!/bin/tcsh

set hdrl = `rinex2hdr $1`

# print line numbers of the start of each block
awk '/[A-z]/ && NR>'"$hdrl"' && $1!~/[A-z]/ {print NR}' $1

# print date at the start of each block in yyyy-mm-dd hh:mm:ss format
# awk '/[A-z]/ && NR>'"$hdrl"' && $1!~/[A-z]/ {printf "20%2.2i-%2.2i-%2.2i %2.2i:%2.2i:%2.2i\n",$1,$2,$3,$4,$5,$6}' $1

# Let it report min, max, median, mean, stdev block size
# nawk
# bc
# sort

# Let it report first and the last block size
