#!/bin/tcsh
#
# Compute the length of a given RINEX file in seconds 
#
# INPUT:
#
# $1      RINEX file
#
# OUTPUT:
#
# Length of RINEX file [seconds] to screen
#
# REQUIRES:
#
# A full installation of GipsyX, in particular, DATE2SEC
#
# Last modified by tschuh-at-princeton.edu

set infile = $1

set yr1 = `awk '/FIRST/ {printf "%04.0f",$1}' $infile`
set mon1 = `awk '/FIRST/ {printf "%02.0f",$2}' $infile`
set day1 = `awk '/FIRST/ {printf "%02.0f",$3}' $infile`
set hr1 = `awk '/FIRST/ {printf "%02.0f",$4}' $infile`
set min1 = `awk '/FIRST/ {printf "%02.0f",$5}' $infile`
set sec1 = `awk '/FIRST/ {printf "%02.0f",$6}' $infile`

set yr2 = `awk '/LAST/ {printf "%04.0f",$1}' $infile`
set mon2 = `awk '/LAST/ {printf "%02.0f",$2}' $infile`
set day2 = `awk '/LAST/ {printf "%02.0f",$3}' $infile`
set hr2 = `awk '/LAST/ {printf "%02.0f",$4}' $infile`
set min2 = `awk '/LAST/ {printf "%02.0f",$5}' $infile`
set sec2 = `awk '/LAST/ {printf "%02.0f",$6}' $infile`

set first = `date2sec $yr1-$mon1-$day1 ${hr1}:${min1}:${sec1}`
set last = `date2sec $yr2-$mon2-$day2 ${hr2}:${min2}:${sec2}`

set length = `echo "$last-$first+1" | bc`

printf "Length of $infile = %.0f seconds\n" $length
