#!/bin/tcsh
#
# pre-process all GEONET_JAPAN/rinex1hz data to run automatically
#
# INPUT:
#
# $1        list of 4-character station/marker code i.e. 0842
# $2        start day of year
# $3        end day of year
#
# AUXILLARY CODE NEEDED:
#
# gzip, bzip2, RNXCMP, rnxTools
#
# Originally written by tschuh-at-princeton.edu, 06/07/2022
# Last modified by tschuh-at-princeton.edu, 06/28/2022

set warnin = 0
if($#argv == 7)then
set rinexdir = $7
set navdir = $7
else if($#argv == 8)then
set rinexdir = $7
set navdir = $8
else
  echo ' '
  echo 'RNX2PRE: eight input arguments expected:'
  echo ' '
  echo '----------> RNX2PRE stlist yr sdoy edoy prideconfig rinexdir [navdir]'
  echo '----------> where stlist is a list of 4-character station/marker code'
  echo '----------> where yr is year'
  echo '----------> where sdoy is start day of year'
  echo '----------> where edoy is end day of year'
  echo '----------> where sps is sampling rate in seconds'
  echo '----------> where prideconfig is file containing PRIDE PPP-AR configuration'
  echo '----------> where rinexdir is directory containing day/station full RINEX files'
  echo '----------> where navdir is directory containing day/station navigation files'
  echo ' '
  @ warnin +=1
  goto label999
endif

#########################################################################

# THIS CODE ONLY WORKS FOR THE STRUCTURE WE'VE DESIGNED ON ORTELIUS

# start in directory with which the station numbers are in

# define variables from inputs
set stlist = $1
set yr = $2
set split = ($yr:as/20/ /)
set yr2 = $split[1]
set sdoy = $3
set edoy = $4
set sps = $5
set prideconfig = $6

# define sequence of days
set nums = `seq -f %03g $sdoy $edoy`
set sznums = `echo ${#nums}`

# loop over marker names
foreach mkr (`cat $stlist`)
    mkdir $mkr
    cd $mkr
    foreach num ($nums[*])
	# get RINEX files for all hours of DoY and corresponding nav file
	# change cp to ln
	# probably need to bzip2 all files in host directory before anything else
	ls $rinexdir/$num/?/{$mkr}*o >! templist
	ls $navdir/$num/{$mkr}*n >> templist
	foreach file ( `cat templist` )
		ln -s $file
	end

	# now concatenate all the RINEX files for each day into 1 file
	rnx2cat {$mkr}{$num}a.{$yr2}o {$mkr}{$num}b.{$yr2}o ; mv cat.rnx temp
	set files = `/usr/bin/ls {$mkr}{$num}[c-x].{$yr2}o`
	foreach file ($files[*])
	    rnx2cat temp $file ; mv -f cat.rnx temp
	end
	rm -rf {$mkr}{$num}[a-x].{$yr2}o
	mv temp {$mkr}{$num}0.{$yr2}o
    end
    cd ..
end

#############################################################################
# this will need to be new function
# put config file in one smart sport and call it on command line

foreach mkr ($mkrs[*])
    # cd into each station directory
    cd $mkr    
    # working path
    set pth = `pwd`
    # actually run PRIDE
    pdp3 -cfg $pth/$prideconfig -m K -s $yr/$sdoy -e $yr/$edoy -n $mkr -i $sps -f $pth/{$mkr}{$sdoy}0.{$yr2}o
    # cd back up to base directory with all stations
    cd ..
end

##############################################################################

label999:
echo ' '
if ($warnin == 1) then
    echo "Script RNX2PRE stopped, $warnin warning message generated"
else
    echo "Script RNX2PRE finished, $warnin warning messages generated"
endif
echo ' '
