#!/bin/tcsh
#
# Compute the length of a given RINEX file in seconds 
#
# INPUT:
#
# $1      RINEX file
#
# OUTPUT:
#
# Length of RINEX file [seconds] to screen
#
# REQUIRES:
#
# A full installation of GipsyX, in particular, DATE2SEC
#
# Originally written by tschuh-at-princeton.edu, 06/17/2021
# Last modified by tschuh-at-princeton.edu, 07/09/2021

set infile = $1

set nrh = `rnx2hdr $infile`

set line = `head -$nrh $infile | awk '/TIME OF FIRST OBS/'`

set yr1 = `printf "%04.0f" $line[1]`
set mo1 = `printf "%02.0f" $line[2]`
set dy1 = `printf "%02.0f" $line[3]`
set hr1 = `printf "%02.0f" $line[4]`
set mn1 = `printf "%02.0f" $line[5]`
set sc1 = `printf "%02.0f" $line[6]`

set line = `head -$nrh $infile | awk '/TIME OF LAST OBS/'`

set yr2 = `printf "%04.0f" $line[1]`
set mo2 = `printf "%02.0f" $line[2]`
set dy2 = `printf "%02.0f" $line[3]`
set hr2 = `printf "%02.0f" $line[4]`
set mn2 = `printf "%02.0f" $line[5]`
set sc2 = `printf "%02.0f" $line[6]`

set first = `date2sec $yr1-$mo1-$dy1 ${hr1}:${mn1}:${sc1}`
set last = `date2sec $yr2-$mo2-$dy2 ${hr2}:${mn2}:${sc2}`

echo "$last-$first+1" | bc
