#!/bin/tcsh
#
# take approx position from RINEX file
# and convert it to lat lon height
#
# INPUT:
#
# OUTPUT:
#
# obsfiles.llh contains lat, lon, height approximate positions
#
# Originally written by tschuh-at-princeton.edu, 07/06/2021

set files = `/usr/bin/ls *.obs`

touch obsfiles.llh

foreach file ($files[*])

	set nrh = `rnx2hdr $file`
	set pos = `awk 'NR < '"$nrh"' && /APPROX POSITION/ {print $1,$2,$3}' $file`
	xyz2llh.py -xyz $pos >> obsfiles.llh
end
