#!/bin/tcsh -f
#
# Add 4 character marker name to RINEX file
# currently without a marker name
#
# INPUT:
#
# $1      RINEX file
# $2      4-character marker name
#
# OUTPUT:
#
# Modified RINEX file
#
# Originally written by tschuh-at-princeton.edu, 09/14/2021

set warnin = 0
if($#argv < 2)then
  echo ' '
  echo 'RNX2MKR: At least two input arguments expected:'
  echo ' '
  echo '----------> RNX2MKR file markername'
  echo '----------> where markername is 4 characters'
  echo ' '
  @ warnin +=1
  goto label999
endif

################################################################################

set mark = `awk '/MARKER NAME/ {print NR; exit}' $1`

# on MacOS need to add '' in beginning for creation of output file
sed -i '' ''"$mark"' s/                                                            /'"$2"'                                                        /' $1

################################################################################
label999:
echo ' '
if ($warnin == 1) then
    echo "Script RNX2MKR stopped, $warnin warning message generated"
else
    echo "Script RNX2MKR finished, $warnin warning messages generated"
endif
echo ' '
