#!/bin/tcsh -f
#
# takes an unaltered RINEX file and
# outputs the approx position along
# with the start and end times
#
# INPUT:
#
# $1     RIENX file
#
# OUTPUT:
#
# output to screen
#
# Originally written by tschuh-at-princeton.edu, 06/25/2021
# Last modified by tschuh-at-princeton.edu, 07/08/2021

# need to comment!

set file = $1

# Find the header bottom
set nrh = `rnx2hdr $file`

set line = `head -$nrh $file | awk '/TIME OF FIRST OBS/'`

set fyr = `printf "%4.4i" $line[1]`
set fmo = `printf "%2.2i" $line[2]`
set fdy = `printf "%2.2i" $line[3]`
set fhr = `printf "%2.2i" $line[4]`
set fmn = `printf "%2.2i" $line[5]`
set fsc = `printf "%9.7f" $line[6]`

set line = `head -$nrh $file | awk '/TIME OF LAST OBS/'`

set lyr = `printf "%4.4i" $line[1]`
set lmo = `printf "%2.2i" $line[2]`
set ldy = `printf "%2.2i" $line[3]`
set lhr = `printf "%2.2i" $line[4]`
set lmn = `printf "%2.2i" $line[5]`
set lsc = `printf "%9.7f" $line[6]`

set pos = `head -$nrh $file | awk '/APPROX POSITION/ {print $1,$2,$3}'`

echo $pos "  " $fyr $fmo $fdy $fhr $fmn $fsc "  " $lyr $lmo $ldy $lhr $lmn $lsc
